print("Hi! Its so nice to meet you!")
name=input("First, what is your name?")
print(f"Hello {name} welcome to the game!")
print("now that we know each other, lets start!")
adjective1=input("adjective?")
animal1=input("animal1")
place1=input("place1")
noun1=input("noun1")
verb1=input("verb1")
adjective2=input("adjective2")
noun2=input("noun2")
animal2=input("animal2")
verb2=input("verb2")
place2=input("place2")
print("ok great job! lets read the story")
print(f"one day a {adjective1} {animal1} went to the {place1}")
print(f"It want a {noun1} so it {verb1} very {adjective2}")
print(f"when it got to the {place1} it saw the {noun2} and its friend the {animal2}")
print(f"after {verb2} they decided to go to the {place2}")
print(f"YAY!!!!!! good job {name}")
print("I cant wait to see you again!")
print("Ok bye!!!")